export const SHOW_ADDING_FORM = 'SHOW_ADDING_FORM';
export const HIDE_ADDING_FORM = 'HIDE_ADDING_FORM';
export const SHOW_TITLE_ERROR = 'SHOW_TITLE_ERROR';
export const ADD_TITLE = 'ADD_TITLE';
export const REMOVE_SLIDE = 'REMOVE_SLIDE';
export const HIDE_SLIDE_ADDING = 'HIDE_SLIDE_ADDING';
